DROP DATABASE IF EXISTS SampleQuiz_RoadSafety;

CREATE DATABASE SampleQuiz_RoadSafety;

USE SampleQuiz_RoadSafety;

CREATE TABLE User (
    ID INT NOT NULL AUTO_INCREMENT,
    UserName VARCHAR(255) NOT NULL UNIQUE,
    UserPassword VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Levels (
    ID INT NOT NULL AUTO_INCREMENT,
    LevelName TEXT NOT NULL,
    LevelImg VARCHAR(255) DEFAULT NULL,
    LevelDescription TEXT DEFAULT NULL,
    LevelURL VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Scores (
    ID INT NOT NULL AUTO_INCREMENT,
    StartDateTime DATETIME NOT NULL,
    LevelID INT NOT NULL,
    Score INT DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (LevelID) REFERENCES Levels(ID)
);